export const users = [
    {
        "_id": "6373a12f35adf024c4a15df3",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$1,350.10",
        "picture": "http://placegold.it/32x32",
        "age": 33,
        "eyeColor": "brown",
        "name": "Huff Blackwell",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "ECLIPSENT",
        "email": "huffblackwell@eclipsent.com",
        "phone": "+1 huffblackwell@eclipsent.com",
        "address": "179 Howard Place, Germanton, Indiana, 27239"
    },
    {
        "_id": "6373a12fd18bd405eaa29388",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$1,282.45",
        "picture": "http://placegold.it/32x32",
        "age": 31,
        "eyeColor": "blue",
        "name": "Krystal Walsh",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "DOGNOSIS",
        "email": "krystalwalsh@dognosis.com",
        "phone": "+1 krystalwalsh@dognosis.com",
        "address": "512 Dinsmore Place, Cartwright, Northern Mariana Islands, 5424"
    },
    {
        "_id": "6373a12f33048fa79f24c989",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$2,961.18",
        "picture": "http://placegold.it/32x32",
        "age": 33,
        "eyeColor": "brown",
        "name": "Mable Clark",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "GREEKER",
        "email": "mableclark@greeker.com",
        "phone": "+1 mableclark@greeker.com",
        "address": "510 Lake Street, Oceola, Rhode Island, 92687"
    },
    {
        "_id": "6373a12f5b62b652fcbbdcf8",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$2,131.08",
        "picture": "http://placegold.it/32x32",
        "age": 32,
        "eyeColor": "blue",
        "name": "Lavonne Anderson",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "CRUSTATIA",
        "email": "lavonneanderson@crustatia.com",
        "phone": "+1 lavonneanderson@crustatia.com",
        "address": "169 Amboy Street, Berlin, Nevada, 58071"
    },
    {
        "_id": "6373a12f93c084af4d91eb66",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$2,445.86",
        "picture": "http://placegold.it/32x32",
        "age": 23,
        "eyeColor": "green",
        "name": "Carroll Hull",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "INFOTRIPS",
        "email": "carrollhull@infotrips.com",
        "phone": "+1 carrollhull@infotrips.com",
        "address": "921 Arlington Avenue, Floris, North Dakota, 49863"
    },
    {
        "_id": "6373a12f8914efc0cd4b8577",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$3,267.09",
        "picture": "http://placegold.it/32x32",
        "age": 31,
        "eyeColor": "blue",
        "name": "Goldie Spencer",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "XEREX",
        "email": "goldiespencer@xerex.com",
        "phone": "+1 goldiespencer@xerex.com",
        "address": "426 Harbor Lane, Joes, Tennessee, 69601"
    },
    {
        "_id": "6373a12f35997abcb394e130",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$1,929.16",
        "picture": "http://placegold.it/32x32",
        "age": 23,
        "eyeColor": "blue",
        "name": "Esmeralda Wright",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "INVENTURE",
        "email": "esmeraldawright@inventure.com",
        "phone": "+1 esmeraldawright@inventure.com",
        "address": "411 Sharon Street, Fairview, Vermont, 81809"
    },
    {
        "_id": "6373a12fc8e64baafa08417d",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$1,788.56",
        "picture": "http://placegold.it/32x32",
        "age": 23,
        "eyeColor": "blue",
        "name": "Corrine Turner",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "ARCTIQ",
        "email": "corrineturner@arctiq.com",
        "phone": "+1 corrineturner@arctiq.com",
        "address": "883 Cozine Avenue, Valmy, Puerto Rico, 45182"
    },
    {
        "_id": "6373a12fb3a8760e1a580ff0",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$1,014.35",
        "picture": "http://placegold.it/32x32",
        "age": 37,
        "eyeColor": "blue",
        "name": "Celeste Bray",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "CEMENTION",
        "email": "celestebray@cemention.com",
        "phone": "+1 celestebray@cemention.com",
        "address": "940 Cheever Place, Mayfair, Guam, 94535"
    },
    {
        "_id": "6373a12ffff2e73c242d75b1",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$3,684.06",
        "picture": "http://placegold.it/32x32",
        "age": 32,
        "eyeColor": "green",
        "name": "Hale Bond",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "ZENSURE",
        "email": "halebond@zensure.com",
        "phone": "+1 halebond@zensure.com",
        "address": "301 Wallabout Street, Felt, Mississippi, 48100"
    },
    {
        "_id": "6373a12f2e873105645dc61c",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$2,541.32",
        "picture": "http://placegold.it/32x32",
        "age": 37,
        "eyeColor": "green",
        "name": "Judith Burnett",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "REALYSIS",
        "email": "judithburnett@realysis.com",
        "phone": "+1 judithburnett@realysis.com",
        "address": "203 Dunne Court, Springville, American Samoa, 34330"
    },
    {
        "_id": "6373a12f468d63e8cf399e1e",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$2,016.96",
        "picture": "http://placegold.it/32x32",
        "age": 24,
        "eyeColor": "green",
        "name": "Essie Campos",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "BICOL",
        "email": "essiecampos@bicol.com",
        "phone": "+1 essiecampos@bicol.com",
        "address": "556 Seacoast Terrace, Eden, New Jersey, 81628"
    },
    {
        "_id": "6373a12fab3d5f23a837cdb8",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$3,230.81",
        "picture": "http://placegold.it/32x32",
        "age": 40,
        "eyeColor": "blue",
        "name": "Candace Craft",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "KEGULAR",
        "email": "candacecraft@kegular.com",
        "phone": "+1 candacecraft@kegular.com",
        "address": "897 Crosby Avenue, Brutus, New Hampshire, 67079"
    },
    {
        "_id": "6373a12f6e1d3295cd0d6c4b",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$2,030.67",
        "picture": "http://placegold.it/32x32",
        "age": 35,
        "eyeColor": "green",
        "name": "Stout Evans",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "ZANYMAX",
        "email": "stoutevans@zanymax.com",
        "phone": "+1 stoutevans@zanymax.com",
        "address": "178 Division Place, Saranap, Wyoming, 17432"
    },
    {
        "_id": "6373a12f1219cbaafd243fb3",
        "isActive": "function(){return!!Math.floor(2*Math.random())}",
        "balance": "$2,749.24",
        "picture": "http://placegold.it/32x32",
        "age": 21,
        "eyeColor": "green",
        "name": "Yolanda Woods",
        "gender": "function(){return e.gender||(this.bool()?\"male\":\"female\")}",
        "company": "ELPRO",
        "email": "yolandawoods@elpro.com",
        "phone": "+1 yolandawoods@elpro.com",
        "address": "161 Hunterfly Place, Chesapeake, Kansas, 60960"
    }
]